// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3haUz3fgsxKJkTN4hXt31gdeADCToZiE',
    appId: '1:512731659209:web:99ee802c16844eb0f5c618',
    messagingSenderId: '512731659209',
    projectId: 'social-media-app-79e8b',
    authDomain: 'social-media-app-79e8b.firebaseapp.com',
    storageBucket: 'social-media-app-79e8b.appspot.com',
    measurementId: 'G-61YPE2T1F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVfmC2jQwRqNHvzBN91uoEaf9Zrq0y5SU',
    appId: '1:512731659209:android:ab611348c134a225f5c618',
    messagingSenderId: '512731659209',
    projectId: 'social-media-app-79e8b',
    storageBucket: 'social-media-app-79e8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz31WHEJ29hRvnyXOfDEGJj9xqHG8fu1c',
    appId: '1:512731659209:ios:564e376d99eba02cf5c618',
    messagingSenderId: '512731659209',
    projectId: 'social-media-app-79e8b',
    storageBucket: 'social-media-app-79e8b.appspot.com',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz31WHEJ29hRvnyXOfDEGJj9xqHG8fu1c',
    appId: '1:512731659209:ios:c56e1902cf85a208f5c618',
    messagingSenderId: '512731659209',
    projectId: 'social-media-app-79e8b',
    storageBucket: 'social-media-app-79e8b.appspot.com',
    iosBundleId: 'com.example.socialmediaapp.RunnerTests',
  );
}
